# Generated by Django 5.1.1 on 2024-10-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_orderstatus_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytime',
            name='delivery_time',
            field=models.DateField(),
        ),
    ]
