# Generated by Django 5.1.1 on 2024-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_alter_deliverytime_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('delivery', 'Delivery Person'), ('client', 'Client'), ('warehouse', 'Warehouse Worker')], max_length=15),
        ),
    ]
