# Generated by Django 5.1.1 on 2024-10-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
