# Generated by Django 5.1.3 on 2024-11-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_supply',
            field=models.BooleanField(default=False, verbose_name='Поставка'),
        ),
    ]
