# Generated by Django 5.1.3 on 2024-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_order_is_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='min_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
