# Generated by Django 5.1.3 on 2024-11-17 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_stock_min_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='departure_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 17)),
        ),
    ]
