# Generated by Django 5.1.3 on 2024-11-17 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0010_alter_order_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 18)),
        ),
    ]
