# Generated by Django 5.1.3 on 2024-11-20 18:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 20)),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('delivery', 'Delivery Person'), ('client', 'Client'), ('warehouse', 'Warehouse Worker'), ('provider', 'Provider')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон может содержать только цифры, знаки (), -, +.', regex='^[0-9\\(\\)\\-\\+]+$')]),
        ),
    ]
