# Generated by Django 5.1.3 on 2024-11-24 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_alter_order_delivery_date_alter_order_departure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='departure_date',
            field=models.DateTimeField(default=datetime.date(2024, 11, 24)),
        ),
    ]
